# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "0.0.1"
# Group identifier for your projects
GROUP = "RESTProvider"
COPYRIGHT = "Novoda ltd"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << "http://oss.sonatype.org/content/repositories/signpost-releases"
repositories.remote << "http://repository.codehaus.org/org/codehaus/jackson/"

JACKSON = ['org.codehaus.jackson:jackson-core-asl:jar:1.4.0', 'org.codehaus.jackson:jackson-mapper-asl:jar:1.4.0']
SIGNPOST = ['oauth.signpost:signpost-core:jar:1.1', 'oauth.signpost:signpost-commonshttp4:jar:1.1']

android_layout = Layout.new
android_layout[:source, :main] = 'src'

desc "The Restprovider project"
define "RESTProvider" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "RESTProvider", :layout => android_layout do
	compile.with SIGNPOST, JACKSON
	compile
	package :jar
  end

  define "RESTProviderLocalTest" do
  end

  define "RESTProviderTest" do
  end

end
